# Generated by Django 4.2.4 on 2023-08-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='board',
        ),
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.CharField(default='999999', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_string',
            field=models.CharField(default='115511', max_length=50),
        ),
    ]
