# Generated by Django 4.2.4 on 2023-08-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_board_game_game_id_game_game_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_palindrome',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_string',
            field=models.CharField(max_length=100),
        ),
    ]
