# Generated by Django 4.2.4 on 2023-08-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_game_is_palindrome_alter_game_game_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
    ]
