# Generated by Django 4.2.4 on 2023-08-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_palindrome',
            field=models.BooleanField(default=False),
        ),
    ]
